Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2103.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ConstituentHTML Demo Add Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "7c839ef3-e7b8-467f-bcc3-eadada753d04", "2eb3ef9c-60c0-43c2-81fb-434b805e26ed", "ConstituentHTML Demo")>
Partial Public Class [ConstituentHTMLDemoAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _constituentid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of System.Guid)
    Private WithEvents _notetitle As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _text As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _html As Global.Blackbaud.AppFx.UIModeling.Core.HtmlField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public Sub New()
        MyBase.New()

        _constituentid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of System.Guid)
        _notetitle = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _text = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _html = New Global.Blackbaud.AppFx.UIModeling.Core.HtmlField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("7c839ef3-e7b8-467f-bcc3-eadada753d04")
        MyBase.DataFormInstanceId = New System.Guid("2eb3ef9c-60c0-43c2-81fb-434b805e26ed")
        MyBase.RecordType = "ConstituentHTML Demo"
        MyBase.FORMHEADER.Value = "Add constituent HTML (demo)"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ssc.htmleditor/ConstituentHTMLDemoAddDataForm.html"

        '
        '_constituentid
        '
        _constituentid.Name = "CONSTITUENTID"
        _constituentid.Caption = "Constituent"
        _constituentid.SearchListId = New System.Guid("fdf9d631-5277-4300-80b3-fdf5fb8850ec")
        _constituentid.EnableQuickFind = True
        _constituentid.EnableAutoSearch = True
        Me.Fields.Add(_constituentid)
        '
        '_notetitle
        '
        _notetitle.Name = "NOTETITLE"
        _notetitle.Caption = "Title"
        _notetitle.MaxLength = 100
        Me.Fields.Add(_notetitle)
        '
        '_text
        '
        _text.Name = "TEXT"
        _text.Caption = "Paste HTML here"
        _text.Description = "The plain text that comprises this design"
        _text.Visible = False
        Me.Fields.Add(_text)
        '
        '_html
        '
        _html.Name = "HTML"
        _html.Caption = "Notes"
        _html.Description = "The HTML that comprises this note"
        _html.AllowImages = True
        _html.AllowStyleTags = True
        _html.EditorType = Global.Blackbaud.AppFx.UIModeling.Core.HtmlEditorType.Advanced
        _html.PasteType = Global.Blackbaud.AppFx.UIModeling.Core.HtmlPasteType.Power
        _html.AllowClasses = True
        _html.AllowConditionalComments = True
        Me.Fields.Add(_html)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Constituent
    ''' </summary>
    <System.ComponentModel.Description("Constituent")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [CONSTITUENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of System.Guid)
        Get
            Return _constituentid
        End Get
    End Property
    
    ''' <summary>
    ''' Title
    ''' </summary>
    <System.ComponentModel.Description("Title")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [NOTETITLE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _notetitle
        End Get
    End Property
    
    ''' <summary>
    ''' The plain text that comprises this design
    ''' </summary>
    <System.ComponentModel.Description("The plain text that comprises this design")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [TEXT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _text
        End Get
    End Property
    
    ''' <summary>
    ''' The HTML that comprises this note
    ''' </summary>
    <System.ComponentModel.Description("The HTML that comprises this note")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [HTML]() As Global.Blackbaud.AppFx.UIModeling.Core.HtmlField
        Get
            Return _html
        End Get
    End Property
    
End Class
